version: "3.6"

services:
  service-registry:
    image: saivulavapati/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway:
    image: saivulavapati/api-gateway
    container_name: api-gateway-container
    ports:
      - "9000:9000"
    networks:
      - spring-cloud-network
    depends_on:
      service-registry:
        condition: service_healthy
    restart: on-failure
    environment:
      JWT_SECRETKEY: ${JWT_SECRETKEY}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
  
  weather-service:
    image: saivulavapati/weather-service
    container_name: weather-service-container
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    depends_on:
      service-registry:
        condition: service_healthy
      api-gateway:
        condition: service_started
    restart: on-failure
    environment:
      OPEN_API_KEY: ${OPEN_API_KEY}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/

  whishlist-service:
    image: saivulavapati/whishlist-service
    container_name: whishlist-service-container
    ports:
      - "8083:8083"
    networks:
      - spring-cloud-network
    depends_on:
      service-registry:
        condition: service_healthy
      api-gateway:
        condition: service_started
      mysql-db:
        condition: service_started
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/wishlistdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  mysql-db:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3307:3306"
    networks:
      - spring-cloud-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wishlistdb  # No MYSQL_USER or MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
