spring:
  application:
    name: weather-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8181}"

openweather:
  api:
    key: c18d907f51bf7046b95d6cc17dac02a5






