spring:
  application:
    name: authentication-service
  jwt:
    jwtCookieName: ${JWT_COOKIE_NAME:weather-jwt-cookie}
    secretKey: ${JWT_SECRETKEY:d05fa4badc91955cd239184b42c1b6f72d2a2f6798798354c0609f876923f41d}
    expiration: ${JWT_EXPIRATION:1800000}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8181}"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.weatherapp.authentication_service.dto.KafkaAuthResponse"
