server:
  port: 8181

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          uri: ${GIT_URL}